### ISSUE TITLE
Log in with random password

### ISSUE THREAD

**Issue by Nur1995** [WebAhead12/Its-A-Me-Mario#2]
The first time you log in, you can use a random password not connected to the account. Afterwards, you must use the password you initially used, and not your actual Github password (unless it's the one you used to log in first). 

Suggestion:
There's also no difference in information when logging in and searching for someone.  There should be a visual and functional difference between the two

**Comment by Iz1cK** [comment]
Intended feature, no way of verifying with github, hence why the user "creates" his account on our website the first time they join , and after that they need to enter the password they initially entered
